tplProjectName: mobilebuilder_tpl_8_0_0_ngx
â†“Menu [ngx.components.UIDynamicMenu-1562069116561]: ğŸ— mobileMenus/Menu.yaml
â†“ChatBot [ngx.components.UISharedRegularComponent-1562052281347]: ğŸ— mobileSharedComponents/ChatBot.yaml
â†“Page [ngx.components.PageComponent-1562069093658]: ğŸ— mobilePages/Page.yaml
â†“testChatBot [ngx.components.PageComponent-1614695600928]: ğŸ— mobilePages/testChatBot.yaml